apiVersion: v1
kind: Service

metadata:
  name: tablemaster-service
  namespace: ns-arav

spec:
  selector:
    app: tablemaster

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer